{{- if .Values.component.master }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vearch-ingress-{{ .Release.Name }}
  namespace: {{ $namespace }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
   - host: {{ .Release.Name }}.{{ .Values.namespace }}{{ .Values.global.base_domain }}
     http:
       paths:
      #  - path: /master(/|$)(.*)
      #    pathType: Prefix
      #    backend:
      #      service:
      #        name: master-service-{{ .Release.Name }}
      #        port: 
      #          number: {{ .Values.master.api_port }}
       - path: /
         pathType: Prefix
         backend:
           service:
             name: router-service-{{ .Release.Name }}
             port: 
               number: {{ .Values.router.port }}
{{ end }}
