{{- if .Values.component.monitor }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
{{- $consul := printf "consul-%s" .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service-{{ .Release.Name }}
  namespace: {{ $namespace }}
spec:
  ports:
    - port: {{ .Values.consul.port }}
      protocol: TCP
      targetPort: {{ .Values.consul.port }}
  selector:
{{ tuple $envAll $namespace $consul | include "helm-toolkit.metadata_labels" | indent 4 }}
{{ end }}
