{{- if .Values.component.router }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
{{- $router := printf "router-%s" .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: router-service-{{ .Release.Name }}
  namespace: {{ $namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.router.port }}
      protocol: TCP
      targetPort: {{ .Values.router.port }}
  selector:
{{ tuple $envAll $namespace $router | include "helm-toolkit.metadata_labels" | indent 4 }}
{{ end }}
