
namespace: vearch

component:
  master: true
  router: true
  ps: true
  monitor: true

image:
  server: vearch/vearch:3.3.4
  grafana: grafana/grafana:6.4.4
  prometheus: prom/prometheus:v2.13.1
  consul: consul:1.6.1
  pull_policy: "IfNotPresent"
  pull_secret: tpaas-itg

# store data,log and other data 
global:
  data: /export/vearch/datas/
  log: /export/vearch/logs/
  level: debug
  self_manage_etcd: false
  signkey: secret
  skip_auth: true
  monitor: /export/vearch/prometheus
  base_domain: .vearch.com

master:
  replicas: 3
  cluster: my-cluster
  labels:
    node_selector_key: vearch-master
    node_selector_value: enabled
  api_port: 8817
  etcd_port: 2378
  etcd_peer_port: 2390
  etcd_client_port: 2370
  pprof_port: 6062
  monitor_port: 8818
  resources:
    enabled: true
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

router:
  replicas: 2
  labels:
    node_selector_key: vearch-router
    node_selector_value: enabled
  port: 9001
  pprof_port: 6061
  monitor_port: 8818
  plugin_path: "plugin"
  resources:
    enabled: true
    requests:
      memory: "2Gi"
      cpu: "2000m"
    limits:
      memory: "4Gi"
      cpu: "4000m"

ps:
  replicas: 1
  labels:
    node_selector_key: vearch-ps
    node_selector_value: enabled
  rpc_port: 8081
  raft_heartbeat_port: 8898
  raft_replicate_port: 8899
  heartbeat-interval: 200 #ms
  raft_retain_logs: 20000000
  raft_replica_concurrency: 1
  raft_snap_concurrency: 1
  raft_truncate_count: 20000
  engine_dwpt_num: 8
  pprof_port: 6060
  private: false
  resources:
    enabled: true
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "8000m"

consul:
  port: 8500
  replicas: 1 

grafana:
  port: 3000
  replicas: 1
  admin_password: !!string 123456
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

prometheus:
  port: 9090
  replicas: 1
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

etcd:
  address: tpaas-etcd-client.tpaas-etcd
  port: 2379
  user: root
  pwd: ""
